# Simple workflow for deploying static content
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Copy Directory
      #   uses: MadaraUchiha/copy-action@0.0.1
      #   with:
      #     # Source file
      #     source: .
      #     # Target file
      #     target: /var/www/digitaalpatientendossier.gds.local/
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          # Artifact name
          name: 'digitaalpatientendossier'
          path: .
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: 'digitaalpatientendossier'
          # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: '/var/www/digitaalpatientendossier.gds.local/html/'
          
      # - name: Copy file
      #   # You may pin to the exact commit or the version.
      #   # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
      #   uses: canastro/copy-action@0.0.2
      #   with:
      #     # Source file
      #     source: 'digitaalpatientendossier.zip'
      #     # Target file
      #     target: '/var/www/digitaalpatiendossier.gds.local/html/'
          
