# Simple workflow for deploying static content
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: 'self-hosted'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Copy Directory
      #   uses: MadaraUchiha/copy-action@0.0.1
      #   with:
      #     # Source file
      #     source: .
      #     # Target file
      #     target: /var/www/digitaalpatientendossier.gds.local/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          # Artifact name
          name: 'digitaalpatientendossier'
          path: .
          
